# Generated by Django 2.0 on 2018-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=25)),
                ('subject', models.CharField(choices=[('', '')], max_length=500)),
                ('message', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='platform_model',
            name='colab_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform_model',
            name='hadoop_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform_model',
            name='jupyter_url',
            field=models.CharField(max_length=100),
        ),
    ]
