# Generated by Django 2.0 on 2018-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181117_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_model',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='subject',
            field=models.CharField(choices=[('Wrong result', 'Wrong result'), ('Help us improve', 'Help us improve')], max_length=500),
        ),
    ]
